services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - data_base:/var/lib/mysql
    networks:
      - netception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - netception

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_files:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - netception

volumes:
  data_base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vboxuser/data/wordpress_db'
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vboxuser/data/wordpress_files'

networks:
  netception:
    driver: bridge
